spring:
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      username: postgres
      password: postgrs
      driver-class-name: org.postgresql.Driver
      maxActive: 100
      initial-size: 5
      min-idle: 10
      validation-query: select 'x'
      testWhileIdle: true
      minEvictableIdleTimeMillis: 60000
      filters: stat,wall  #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
